version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: questionnaire
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/questionnaire
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: questionnaire-postgres
    restart: always
    environment:
      POSTGRES_DB: questionnaire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"